trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    echo "Current directory:"
    pwd
    echo "Directory contents:"
    ls -la
    echo "Looking for app folders:"
    find . -name "app" -type d
  displayName: 'Debug: Show directory structure'
