trigger:
- main
pool:
  vmImage: ubuntu-latest
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'app'  # Changed from 'devops_project/tree/main/app' to 'app'
- script: |
    cd app
    node app.js
  displayName: 'Run Node.js App'