apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fintech-app-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring  
spec:
  selector:
    matchLabels:
      app: fintech-app  
  namespaceSelector:
    matchNames:
      - fintech-dev  
  endpoints:
    - port: http        
      path: /metrics
      interval: 15s